<?php
$downloads = $this->downloads->toArray();
?>

<div class="panel panel-default">
    <div class="panel-heading">新增檔案</div>
    <div class="panel-body">
        <form id="form-download" class="form-horizontal" method="post" enctype="multipart/form-data" action="/admin/download/add">
            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Title</label>
                <div class="col-sm-4">
                    <input type="text" id="title" class="form-control" name="title" value="<?php echo $this->title ?>"/>
                </div>
            </div>
            <div class="form-group">
                <label for="title" class="control-label col-sm-2">File</label>
                <div class="col-sm-10">
                    <input type="file" name="file"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <ul class="list-group">
            <?php foreach ($downloads as $download): ?>
                <li class="list-group-item" style="overflow: hidden;">
                    <em><?php echo $download['title'] ?></em>
                    <a class="btn btn-danger pull-right" href="/admin/download/del/id/<?php echo $download['id']; ?>">刪除</a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>