<?php
$downloads = $this->downloads->toArray();
?>

<table>
    <thead>
    <tr>
        <td>標題</td>
        <td>刪除</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($downloads as $download): ?>
        <tr>
            <td><?php echo $download['title'] ?></td>
            <td><a href="/admin/download/del/id/<?php echo $download['id']; ?>">刪除</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div>新增</div>
<form method="post" enctype="multipart/form-data" action="/admin/download/add">
    Title <input type="text" name="title"/><br>
    File <input type="file" name="file"/><br>
    <input type="submit"/>
</form>