web:
  build: .
  ports:
    - 8080:80
  links:
    - db
  environment:
    APPLICATION_ENV: production

db:
  image: mariadb:10
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: default
