<div class="panel panel-default">
    <div class="panel-body">
        <form id="form-about" class="form-horizontal" action="/admin/auth/login" method="post">
            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Password</label>
                <div class="col-sm-4">
                    <input type="text" id="title" class="form-control" name="password"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">登入</button>
                </div>
            </div>
        </form>
    </div>
</div>
