<!doctype html>
<html lang="zh-TW">
<head>
    <title>scsmartflo.com</title>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
</head>
<body>
<div>
    <a href="/admin/about">About</a>
    <a href="/admin/product">Product</a>
    <a href="/admin/download">Download</a>
    <a href="/admin/contact">Contact</a>
</div>
<div id="content"><?php echo $this->layout()->content; ?></div>
</body>
</html>
