<!doctype html>
<html lang="zh-TW">
<head>
    <title>scsmartflo.com</title>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <style>
        * {
            font-size: 12px;
        }
        a {
            text-decoration: none;
        }
    </style>
</head>
<body>
<div id="content"><?php echo $this->layout()->content; ?></div>
</body>
</html>
