<?php

$categories = $this->categories;

$slides = array(
    array(
        'bg' => 'bg1',                    //背景圖
        'description' => 'We are compnay'   //背景簡介
    ),
    array(
        'bg' => 'bg1',
        'description' => '2222'
    ),
    array(
        'bg' => 'bg1',
        'description' => '333'
    ),
);

$products = array(
    array(
        'id' => 'product',                 //產品id 同時也是圖片id
        'name' => 'ProductName01',          //產品名稱
        'description' => 'Super.........'   //產品敘述
    ),
    array(
        'id' => 'product',                 //產品id 同時也是圖片id
        'name' => 'ProductName01',          //產品名稱
        'description' => 'Super.........'   //產品敘述
    ),
    array(
        'id' => 'product',                 //產品id 同時也是圖片id
        'name' => 'ProductName01',          //產品名稱
        'description' => 'Super.........'   //產品敘述
    ),
    array(
        'id' => 'product',                 //產品id 同時也是圖片id
        'name' => 'ProductName01',          //產品名稱
        'description' => 'Super.........'   //產品敘述
    ),
    array(
        'id' => 'product',                 //產品id 同時也是圖片id
        'name' => 'ProductName01',          //產品名稱
        'description' => 'Super.........'   //產品敘述
    ),
);


?>


<link rel="stylesheet" href="/css/index.css">
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.8/slick.css"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.8/slick.min.js"></script>
<script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>

<div class="navbar">
    <!--微縮選單-->
    <span class="navbar-brand" href="#">
        <img src="/img/logo.png">
    </span>
    <span class="navbar-list">
        <ul>
            <li class="navbar-item current bg-red" data-target="intro"><a href="#">About us</a></li>
            <li class="navbar-item bg-blue" data-target="products"><a href="#">Products</a></li>
            <li class="navbar-item bg-red" data-target="contact-us"><a href="#contact">Contact</a></li>
            <li class="bg-blue"><a href="#">Download</a></li>
        </ul>
    </span>
</div>
<div class="container">
    <div class="intro">
        <div class="intro-carousel">
            <?php foreach ($slides as $key => $slide) { ?>
            <div class="intro-content<?php echo $key == 0 ? ' current' : ''; ?>">
                <img src="/img/<?php echo $slide['bg']; ?>.jpg">
                <h3><?php echo $slide['description']; ?></h3>
            </div>
            <?php } ?>
        </div>
        <div class="next-btn">
            <i class="fa fa-angle-left"></i>
        </div>
        <div class="prev-btn">
            <i class="fa fa-angle-right"></i>
        </div>
    </div>

    <div class="intro-detail">
        <h4>Lorem ipsum dolor sit amet</h4>
        <p class="left">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p class="right">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>

    <div class="products">
        <div class="products-kinds">
            <ul>
                <?php foreach ($categories as $key => $category) { ?>
                    <li <?php echo $key == 0 ? 'class="current"' : ''; ?> data-kind="<?php echo $category['id']?>"><span class="arrow"></span><?php echo $category['title']?></li>
                <?php } ?>
            </ul>
        </div>
        <div class="product-container">
            <?php foreach ($products as $product) { ?>
            <div class="product-item">
                <img src="/img/<?php echo $product['id']; ?>.jpg">
                <div class="product-name"><?php echo $product['name']; ?></div>
                <div class="product-describe"><?php echo $product['description']; ?></div>
            </div>
            <?php } ?>
        </div>
        <div class="product-detail">
            <div class="product-detail-container">
                <div class="product-image">
                    <img src="/img/product.jpg">
                </div>
                <div class="product-describe">
                    <h3>I am product</h3>
                    <p>Given a jQuery object that represents a set of DOM elements, the .eq() method constructs a new jQuery object from one element within that set. The supplied index identifies the position of this element in the set.</p>
                </div>
                <div class="btn-set">
                    <div class="btn-close"><i class="fa fa-times"></i></div>
                    <div class="btn-ask"><i class="fa fa-commenting-o"></i></div>
                </div>
            </div>
        </div>
    </div>

    <div class="contact-us">
        <div class="contact-form">
            <form novalidate>
                <div class="field">
                    <input type="text" class="form-control required" id="username" name="username" placeholder="NAME" required minlength="2">
                </div>
                <div class="field">
                    <input type="text" class="form-control required email" id="email" name="email" placeholder="EMAIL">
                </div>
                <div class="field">
                    <input type="text" class="form-control" id="phone" placeholder="PHONE">
                </div>
                <div class="field">
                    <input type="text" class="form-control" id="title" name="title" placeholder="TITLE">>
                </div>
                <div class="field field-message">
                    <textarea class="form-control" id="message" name="message" placeholder="MESSAGE"></textarea>>
                </div>
                <input type="submit" class="btn btn-default btn-submit" value="Submit"></input>
            </form>
        </div>
    </div>
</div>
<script src="/js/scsmartflo-compressed.js"></script>