<link rel="stylesheet" href="/css/index.css">
<script src="/js/scsmartflo-compressed.js"></script>

<div class="navbar navbar-default navbar-fixed-top">
    <!--微縮選單-->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-header"
                aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img src="/img/logo.png">
        </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-header">
        <ul class="nav navbar-nav navbar-right">
            <li class="current bg-red"><a href="#">About us</a></li>
            <li class="bg-blue"><a href="#">Products</a></li>
            <li class="bg-red"><a href="#contact">Contact</a></li>
            <li class="bg-blue"><a href="#">Download</a></li>
        </ul>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div id="about-us-slides" class="carousel slide" data-ride="carousel" data-interval="false">
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="/img/bg2.jpg" alt="...">

                    <div class="carousel-content-left">
                        <p>C.F Martin & Co. (www.martinguitar.com) has been creating the finest instruments in the world
                            for over 175 years. It continues to innovate, introducing techniques and features that have
                            become industry standards including X-bracing, the 14-fret guitar and the "Dreadnought"
                            size. One of the world's leading acoustic instrument makers, Martin guitars are hand-made by
                            skilled craftsmen and women, who use a combination of new design and techniques along with
                            those introduced by the company founder.</p>
                    </div>
                    <div class="carousel-caption">
                        <h3 class="bg-red">Lorem ipsum dolor sit amet, consetetur sadipscing elitr</h3>
                        <h4 class="bg-red">Lorem ipsum dolor sit amet, consetetur sadipscing elitr</h4>
                    </div>
                </div>
                <div class="item">
                    <img src="/img/bg1.jpg" alt="...">

                    <div class="carousel-content-left">
                        <p>C.F Martin & Co. (www.martinguitar.com) has been creating the finest instruments in the world
                            for over 175 years. It continues to innovate, introducing techniques and features that have
                            become industry standards including X-bracing, the 14-fret guitar and the "Dreadnought"
                            size. One of the world's leading acoustic instrument makers, Martin guitars are hand-made by
                            skilled craftsmen and women, who use a combination of new design and techniques along with
                            those introduced by the company founder.</p>
                    </div>
                    <div class="carousel-caption">
                        <h3 class="bg-red">Lorem ipsum dolor sit amet, consetetur sadipscing elitr</h3>
                        <h4 class="bg-red">Lorem ipsum dolor sit amet, consetetur sadipscing elitr</h4>
                    </div>
                </div>
            </div>

            <a class="left carousel-control" href="#about-us-slides" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#about-us-slides" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="row">

        <ul class="nav nav-justified">
            <li class="current"><a href="#">brake</a></li>
            <li><a href="#">cpe fitting</a></li>
            <li><a href="#">convoluted fitting</a></li>
            <li><a href="#">adapter</a></li>
            <li><a href="#">others</a></li>
        </ul>

        <div class="col-sm-8 col-sm-offset-2 products-items">
            <div class="col-xs-6 col-sm-3 item">
                <div class="item-image">
                    <img src="/img/product.jpg" alt="...">
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 item">
                <div class="item-image">
                    <img src="/img/product.jpg" alt="...">
                </div>
                <div class="item-title">
                    <h5 class="product-title">Lorem ipsum</h5>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 item">
                <div class="item-image">
                    <img src="/img/product.jpg" alt="...">
                </div>
                <div class="item-title">
                    <h5 class="product-title">Lorem ipsum</h5>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 item">
                <div class="item-image">
                    <img src="/img/product.jpg" alt="...">
                </div>
                <div class="item-title">
                    <h5 class="product-title">Lorem ipsum</h5>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 item">
                <div class="item-image">
                    <img src="/img/product.jpg" alt="...">
                </div>
                <div class="item-title">
                    <h5 class="product-title">Lorem ipsum</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="contact-us" name="contact">
        <div class="contact-form">
            <form>
                <div class="row">
                    <div class="form-group col-md-4">
                        <input type="email" class="form-control" id="username" placeholder="NAME">
                    </div>
                    <div class="form-group col-md-4">
                        <input type="email" class="form-control" id="email" placeholder="EMAIL">
                    </div>
                    <div class="form-group col-md-4">
                        <input type="text" class="form-control" id="phone" placeholder="PHONE">
                    </div>
                </div>
                <div class="row content-form">
                    <div class="form-group col-md-4">
                        <input type="text" class="form-control" id="title" placeholder="TITLE">
                    </div>
                    <div class="form-group col-md-6">
                        <textarea class="form-control" id="message" placeholder="Message"></textarea>
                    </div>
                    <div class="form-group col-md-2">
                        <button type="submit" class="btn btn-default btn-submit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div id="product-modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="col-sm-6">
                    <h4 class="product-title">Lorem ipsum</h4>

                    <p class="product-details">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
                        eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos
                        et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus
                        est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                        diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
                        voluptua.</p>
                </div>
                <div class="col-sm-6 product-image">
                    <img src="./images/product.jpg" alt="...">
                    <button type="button" class="btn btn-default btn-lg btn-close">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
