<style>
    body, html {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
    }
    .container {
        width: 900px;
        height: 600px;
        position: absolute;
        top: 50%;
        left: 50%;
        margin-top: -300px;
        margin-left: -450px;
    }
    .page {
        width: 100%;
        height: 100%;
    }
</style>
<div class="container">
    <img src="/img/bg.jpg" class="page"></div>
</div>