<form method="post" action="/admin/contact/save" enctype="multipart/form-data">
    Company Title: <input type="text" name="title" value="<?php echo $this->info['title']?>"/><br/>
    Address: <input type="text" name="address" value="<?php echo $this->info['address']?>"/><br/>
    Phone: <input type="text" name="phone" value="<?php echo $this->info['phone']?>"/><br/>
    Email: <input type="text" name="email" value="<?php echo $this->info['email']?>"/><br/>
    <input type="submit" />
</form>
