<?php

$this->pic;

?>

<div class="panel panel-default">
    <div class="panel-heading">關於我們</div>
    <div class="panel-body">
        <form id="form-about" class="form-horizontal" action="/admin/about/save" enctype="multipart/form-data" method="post">
            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Title</label>
                <div class="col-sm-4">
                    <input type="text" id="title" class="form-control" name="title" value="<?php echo $this->title ?>"/>
                </div>
            </div>
            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Pic</label>
                <div class="col-sm-4">
                    <input type="file" class="form-control" name="pic">
                </div>
                <div class="col-sm-6">
                    <a href="#" class="thumbnail">
                        <img src="/upload/<?php echo $this->pic; ?>">
                    </a>
                </div>
            </div>
            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Description</label>
                <div class="col-sm-10">
                    <textarea class="form-control" rows="6" name="description"><?php echo $this->description ?></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">送出修改</button>
                </div>
            </div>
        </form>
    </div>
</div>
