<?php
$sliderShows = $this->sliderShows;
?>

<div class="panel panel-default">
    <div class="panel-heading">新增幻燈片及說明</div>
    <div class="panel-body">
        <form id="form-download" class="form-horizontal" method="post" enctype="multipart/form-data" action="/admin/home/add">
            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Image</label>
                <div class="col-sm-4">
                    <input type="file" class="form-control" name="pic">
                </div>
            </div>
            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Description</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="description">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">新增</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">目前幻燈片</div>
    <div class="panel-body">
        <?php
        $isClose = true;

        foreach ($sliderShows as $index => $sliderShow):
            if ($index % 4 == 0) {
                $isClose = false;
                echo '<div class="row">';
            }
        ?>
                <div class="col-sm-3 home-slider" style="overflow: hidden;">
                    <form method="post" enctype="multipart/form-data" action="/admin/home/upd/id/<?php echo $sliderShow['id']; ?>">
                        <div class="form-group">
                            <label class="control-label">Description</label>
                            <input type="text" id="title" class="form-control" name="description" value="<?php echo $sliderShow['description']; ?>"/>
                        </div>
                        <div class="form-group">
                            <input type="file" class="form-control modify-pic" name="pic"/>
                        </div>
                        <a href="#" class="thumbnail">
                            <img src="/upload/<?php echo $sliderShow['pic'] ?>"/>
                        </a>

                        <div class="btn-group">
                            <input type="submit" class="btn btn-primary" value="送出修改"/>
                            <a class="btn btn-danger pull-right btn-del" href="/admin/home/del/id/<?php echo $index; ?>">刪除</a>
                        </div>
                    </form>
                </div>
            <?php
            if ($index % 4 === 3):
                $isClose = true;
            ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if (!$isClose) echo "</div>"; ?>
    </div>
</div>

<script>
    $(function () {
        $('.modify-pic').change(function () {
            $(this).closest('.home-slider')
                .find('.thumbnail')
                .hide();
        });

        $('.btn-del').click(function (e) {
            if (!confirm('確認刪除？')) {
                e.preventDefault();
            }
        });
    });
</script>
