<?php
$products = $this->products->toArray();

$categories = array();

foreach ($this->category->toArray() as $item) {
    $categories[$item['id']] = $item;
}

?>

<div class="panel panel-default">
    <div class="panel-heading">新增產品分類</div>
    <div class="panel-body">
        <form class="form-inline" method="post" action="/admin/product/add-category">
            <div class="form-group">
                <label for="product-kind" class="control-label col-sm-2">Title</label>
                <div class="col-sm-4">
                    <input type="text" id="product-kind"  class="form-control" name="title">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">新增</button>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">目前產品分類</div>
    <div class="panel-body">
        <ul class="list-group" style="margin-top: 20px;">
            <?php foreach ($categories as $category): ?>
                <li class="list-group-item" style="overflow: hidden;">
                    <em><?php echo $category['title'] ?></em>
                    <a class="btn btn-danger pull-right" href="/admin/product/del-category/id/<?php echo $category['id']; ?>">刪除</a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">新增產品</div>
    <div class="panel-body">
        <form id="form-download" class="form-horizontal" method="post" enctype="multipart/form-data" action="/admin/product/add">

            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Title</label>
                <div class="col-sm-4">
                    <input type="text" id="title" class="form-control" name="title">
                </div>
            </div>

            <div class="form-group">
                <label for="title" class="control-label col-sm-2">Category</label>
                <div class="col-sm-4">
                    <select id="category" class="form-control" name="category">
                        <?php foreach ($categories as $category): ?>
                            <option value="<?php echo $category['id'] ?>"><?php echo $category['title'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="description" class="control-label col-sm-2">Description</label>
                <div class="col-sm-10">
                    <textarea id="description" class="form-control" rows="6" name="description"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="pic" class="control-label col-sm-2">Image</label>
                <div class="col-sm-10">
                    <input type="file" id="pic" class="form-control" name="pic">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">新增</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">現有產品</div>
    <div class="panel-body">
        <ul class="list-group">
            <?php
            $isClose = true;

            foreach ($products as $index => $product):
                if ($index % 4 == 0) {
                    $isClose = false;
                    echo '<div class="row">';
                }
            ?>
                <div class="col-sm-3 product-info" style="overflow: hidden;">
                    <form method="post" enctype="multipart/form-data" action="/admin/product/upd/id/<?php echo $product['id']; ?>">
                        <div class="form-group">
                            <label class="control-label">Title</label>
                            <input type="text" class="form-control" name="title" value="<?php echo $product['title'] ?>"/>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Category</label>
                            <select class="form-control" name="category">
                                <?php foreach ($categories as $category):?>
                                    <?php if ($categories[$product['category_id']]['title'] == $category['title']): ?>
                                        <option value="<?php echo $category['id'] ?>" selected><?php echo $category['title'] ?></option>
                                    <?php else: ?>
                                        <option value="<?php echo $category['id'] ?>"><?php echo $category['title'] ?></option>
                                    <?php endif ?>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Category</label>
                            <textarea class="form-control" rows="6" name="description"><?php echo $product['description'] ?></textarea>
                        </div>

                        <div class="form-group">
                            <input type="file" class="form-control modify-pic" name="pic" value="更換圖片"/>
                        </div>

                        <a href="#" class="thumbnail">
                            <img src="/upload/<?php echo $product['pic']; ?>">
                        </a>

                        <div class="btn-group">
                            <input type="submit" class="btn btn-primary" value="送出修改"/>
                            <a class="btn btn-danger pull-right btn-del" href="/admin/product/del/id/<?php echo $product['id']; ?>">刪除</a>
                        </div>
                    </form>
                </div>

                <?php
                if ($index % 4 === 3):
                    $isClose = true;
                    ?>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if (!$isClose) echo "</div>"; ?>
        </ul>
    </div>
</div>

<script>
    $(function () {
        $('.modify-pic').change(function () {
            $(this).closest('.product-info')
                .find('.thumbnail')
                .hide();
        });

        $('.btn-del').click(function (e) {
            if (!confirm('確認刪除？')) {
                e.preventDefault();
            }
        });
    });
</script>