<?php
$products = $this->products->toArray();

$categories = array();

foreach ($this->category->toArray() as $item) {
    $categories[$item['id']] = $item;
}

?>
<table>
    <thead>
    <tr>
        <td>分類</td>
        <td>標題</td>
        <td>圖片</td>
        <td>說明</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($products as $product): ?>
    <tr>
        <td><?php echo $categories[$product['category_id']]['title'] ?></td>
        <td><?php echo $product['title'] ?></td>
        <td><img src="/upload/<?php echo $product['pic'] ?>"></td>
        <td><?php echo $product['description'] ?></td>
        <td><a href="/admin/product/del/id/<?php echo $product['id']; ?>">刪除</a></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div>新增</div>
<form method="post" enctype="multipart/form-data" action="/admin/product/add">
    category <select name="category">
        <?php foreach ($categories as $category): ?>
            <option value="<?php echo $category['id'] ?>"><?php echo $category['title'] ?></option>
        <?php endforeach; ?>
    </select><br>
    Title <input type="text" name="title"/><br>
    Desc <input type="text" name="description"/><br>
    Pic <input type="file" name="pic"/><br>
    <input type="submit"/>
</form>

<table>
    <thead>
    <tr>
        <td>標題</td>
        <td>刪除</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($categories as $category): ?>
        <tr>
            <td><?php echo $category['title'] ?></td>
            <td><a href="/admin/product/del-category/id/<?php echo $category['id']; ?>">刪除</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div>Add category</div>
<form method="post" action="/admin/product/add-category">
    Title <input type="text" name="title"/></br>
    <input type="submit"/>
</form>